---

- hosts: all
  vars_prompt:
    - name: samba_server_username
      prompt: Samba Server Username
      default: ansible

    - name: samba_server_password
      prompt: Samba Server Password
      default: ansible

    - name: samba_server_domain
      prompt: Samba Server Domain
      default: ansible

- hosts: all
  become: yes
  roles:
    - common
    - flatpak

- hosts: data_source_mounts
  become: yes
  roles:
    - data_source_mounts

- hosts: apt
  become: yes
  roles:
    - apt

- hosts: samba_server
  become: yes
  roles:
    - samba_server
