---

- hosts: all
  vars_prompt:
    - name: samba_server_username
      prompt: Samba Server Username
      default: dr720

    - name: samba_server_password
      prompt: Samba Server Password
      default: dr720

    - name: samba_server_domain
      prompt: Samba Server Domain
      default: dr720

- hosts: apt
  roles:
    - apt
    - common
    - emby
