---

- hosts: all
  vars_prompt:
    - name: samba_server_username
      prompt: Samba Server Username
      default: dr720

    - name: samba_server_password
      prompt: Samba Server Password
      default: dr720

    - name: samba_server_domain
      prompt: Samba Server Domain
      default: dr720

- hosts: all
  become: yes
  roles:
    - common

- hosts: data_source_mounts
  become: yes
  roles:
    - data_source_mounts

- hosts: apt
  become: yes
  roles:
    - apt
