---

- name: Apply all available patches
  community.general.zypper:
    name: '*'
    state: latest
    type: patch

- name: Install common packages
  community.general.zypper:
    state: present
    name:
      - amarok
      - fd
      - fish
      - flatpak
      - fzf
      - gkrellm
      - neovim
      - openssl
      - tmux
      - vlc

- name: Install samba
  community.general.zypper:
    name: samba*
    state: present

- name: Start smb.service
  ansible.builtin.service:
    name: smb.service
    state: started
    enabled: yes

- name: Start nmb.service
  ansible.builtin.service:
    name: nmb.service
    state: started
    enabled: yes
