---

- name: FlatPak Add Flat Husband
  ansible.builtin.command: "flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo"

- name: FlatPak Install Brave
  community.general.flatpak:
    name: com.brave.Browser
    state: present

