---

- name: Mount remote drives
  ansible.builtin.include_role:
    name: mounts
    tasks_from: mounts

- name: Distribution verification
  ansible.builtin.debug:
    var: ansible_distribution
    verbosity: 2
