---

- name: the list
  debug:
    msg: "{{ item.name }}"
  with_items:
    " {{ emby_mounts }}"
  when: false

- name: Retrieve host vars
  debug:
    var=hostvars[inventory_hostname][ansible_hostname]
  when: true

- name: Template file to smbcredentials
  ansible.builtin.template:
    src: templates/smbcredentials.j2
    dest: "/home/{{ ansible_user }}/.smbcredentials"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Mount local 3TB to fstab
  ansible.posix.mount:
    fstype: ext4
    src: /dev/sdb1
    path: /media/3TB
    state: present

- name: Mount local 4TB to fstab
  ansible.posix.mount:
    fstype: ext4
    src: /dev/sdc1
    path: /media/4TB
    state: present

- name: Mount with Postfix
  ansible.posix.mount:
    fstype: cifs
    opts: "credentials=/home/{{ ansible_user }}/.smbcredentials,uid={{ samba_server_username }},gid={{ samba_server_username }}"
    src: "//{{ host_server }}/{{ item.name }}"
    path: "{{ item.core_path }}"
    state: mounted
  with_items:
    "{{ single_mounts }}"
