---

- name: the list
  debug:
    msg: "{{ item.name }}"
  with_items:
    " {{ single_mounts }}"

# - name: Mount Share
#   become: true
#   mount:
#     path: "{{ item.value.mountpoint }}"
#     src: "{{ cifs_url }}"
#     fstype: "cifs"
#     opts: "{{ mount_opts_cat }}"
#     passno: "{{ item.value.passno | default(omit) }}"
#     state: mounted

# - name: Template file to smbcredentials
#   ansible.builtin.template:
#     src: templates/smbcredentials.j2
#     dest: "/home/{{ ansible_user }}/.smbcredentials"
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: "0644"

- name: Mount with Postfix
  become: yes
  ansible.posix.mount:
    src: "/{{ item.name }}"
    opts: "credentials=/home/{{ ansible_user }}/.smbcredentials,uid=444,gid=1"
    fstype: cifs
    path: "{{ item.core_path }}"
    state: mounted
  with_items:
    "{{ single_mounts }}"
