---

- name: the list
  debug:
    msg: "{{ item.name }}"
  with_items:
    "{{ single_mounts }}"


- name: Make mountable directories
  file:
    path: "/media/{{ item.name }}"
    state: directory
  with_items:
    "{{ single_mounts }}"

- name: Template file to smbcredentials
  ansible.builtin.template:
    src: templates/smbcredentials.j2
    dest: "/home/{{ ansible_user }}/.smbcredentials"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Mount with Postfix
  become: yes
  ansible.posix.mount:
    src: "{{ item.name }}"
    opts: "credentials=/home/{{ ansible_user }}/.smbcredentials,uid=444,gid=1"
    fstype: "cifs"
    path: "{{ item.core_path }}"
    state: mounted
  with_items:
    "{{ single_mounts }}"
